---
driver:
  name: vagrant

  synced_folders:
    - ["../app", "/minions"]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu14
    driver:
      box: chef/ubuntu-14.10
      network:
        - ["forwarded_port", {guest: 4567, host: 4567}]
  - name: centos66
    driver:
      box: chef/centos-66
      network:
        - ["forwarded_port", {guest: 5678, host: 5678}]

suites:
  - name: wdiy
    run_list:
      - wdiy
