---
driver:
  name: vagrant

  synced_folders:
    - ["../app", "/minions"]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu14
    driver:
      box: chef/ubuntu-14.10

suites:
  - name: wdiy
